version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - AUTH_CONNECTION=${AUTH_CONNECTION}
      - ENCODE_SECRET=${ENCODE_SECRET}
      - DB_CONNECTION=${DB_CONNECTION}  # Reference your DB connection string
    ports:
      - "5000:5000"  # Expose port for API calls
    volumes:
      - .:/app
    restart: always

